{"text":"\n"}
{"text":"Artificial intelligence (AI) has been used in applications throughout industry and academia. AI, like electricity or computers, is a general-purpose technology that has a multitude of applications. It has been used in fields of language translation, image recognition, credit scoring, e-commerce and other domains.[1]\n"}
{"text":"A recommendation system predicts the rating or preference a user would give to an item.[2][3] Artificial intelligence recommendation systems are designed to offer suggestions based on previous behavior. These systems have been used by companies such as Netflix, Amazon, and YouTube, where they generate personalized playlists, product suggestions, and video recommendations.[4][5]\n"}
{"text":"Machine learning is also used in web feeds such as for determining which posts should show up in social media feeds.[6][7] Various types of social media analysis also make use of machine learning[8][9] and there is research into its use for (semi-)automated tagging/enhancement/correction of online misinformation and related filter bubbles.[10][11][12]\n"}
{"text":"AI is used to target web advertisements to those most likely to click or engage in them. It is also used to increase time spent on a website by selecting attractive content for the viewer. It can predict or generalize the behavior of customers from their digital footprints.[13] Both AdSense[citation needed] and Facebook[14] use AI for advertising.\n"}
{"text":"Online gambling companies use AI to improve customer targeting.[15]\n"}
{"text":"Personality computing AI models add psychological targeting to more traditional social demographics or behavioral targeting.[16] AI has been used to customize shopping options and personalize offers.[17]\n"}
{"text":"Intelligent personal assistants use AI to understand many natural language requests in other ways than rudimentary commands. Common examples are Apple's Siri, Amazon's Alexa, and a more recent AI, ChatGPT by OpenAI.[18]\n"}
{"text":"Search engines that use artificial intelligence include Google Search[19] and Bing Chat.\n"}
{"text":"Machine learning can be used to fight against spam, scams, and phishing. It can scrutinize the contents of spam and phishing attacks to identify any malicious elements.[20] Numerous models built on machine learning algorithms exhibit exceptional performance with accuracies over 90% in distinguishing between spam and legitimate emails.[21]\n"}
{"text":"AI has been used to automatically translate spoken language and textual content, in products such as Microsoft Translator, Google Translate and DeepL Translator.[22] Additionally, research and development are in progress to decode and conduct animal communication.[23][24]\n"}
{"text":"AI has been used in facial recognition systems, with a 99% accuracy rate. Some examples are Apple's Face ID and Android's Face Unlock, which are used to secure mobile devices.[25]\n"}
{"text":"Image labeling has been used by Google to detect products in photos and to allow people to search based on a photo. Image labeling has also been demonstrated to generate speech to describe images to blind people. [26] Facebook's DeepFace identifies human faces in digital images.\n"}
{"text":"Games have been a major application[relevant?] of AI's capabilities since the 1950s. In the 21st century, AIs have produced superhuman results in many games, including chess (Deep Blue), Jeopardy! (Watson),[27] Go (AlphaGo),[28][29][30][31][32][33][34] poker (Pluribus[35] and Cepheus),[36] E-sports (StarCraft),[37][38] and general game playing (AlphaZero[39][40][41] and MuZero).[42][43][44][45] AI has replaced hand-coded algorithms in most chess programs.[46] Unlike go or chess, poker is an imperfect-information game, so a program that plays poker has to reason under uncertainty. The general game players work using feedback from the game system, without knowing the rules.\n"}
{"text":"AI for Good is an ITU initiative supporting institutions employing AI to tackle some of the world's greatest economic and social challenges. For example, the University of Southern California launched the Center for Artificial Intelligence in Society, with the goal of using AI to address problems such as homelessness. At Stanford, researchers use AI to analyze satellite images to identify high poverty areas.[47]\n"}
{"text":"In agriculture, AI has helped farmers identify areas that need irrigation, fertilization, pesticide treatments or increasing yield.[48] Agronomists use AI to conduct research and development. AI has been used to predict the ripening time for crops such as tomatoes,[49] monitor soil moisture, operate agricultural robots, conduct predictive analytics,[50][51] classify livestock pig call emotions,[23] automate greenhouses,[52] detect diseases and pests,[53][54] and save water.[55]\n"}
{"text":"Cyber security companies are adopting neural networks, machine learning, and natural language processing to improve their systems.[56]\n"}
{"text":"Applications of AI in cyber security include:\n"}
{"text":"Google fraud czar Shuman Ghosemajumder has said that AI will be used to completely automate most cyber security operations over time.[58]\n"}
{"text":"AI tutors allow students to get one-on-one help. They can reduce anxiety and stress for students stemming from tutor labs or human tutors.[59]\n"}
{"text":"AI can create a dysfunctional environment with revenge effects[60] such as technology that hinders students' ability to stay on task.[61] In another scenario, AI can provide early prediction of student success in a virtual learning environment (VLE) such as Moodle.[62]\n"}
{"text":"In the education process, students can personalize their training with the help of artificial intelligence. And for teaching professionals, the technology provided by AI can improve the quality of the educational process and teaching skills.[63]\n"}
{"text":"AI text detectors can be used to scan essays generated by artificial intelligence in order to try to establish genuine authorship. However, a study found that seven of the most used of these detectors often wrongly flagged articles written by those whose first language was not English as AI-generated, thus discriminating against so called 'non-native' English speakers.[64]\n"}
{"text":"Financial institutions have long used artificial neural network systems to detect charges or claims outside of the norm, flagging these for human investigation. The use of AI in banking began in 1987 when Security Pacific National Bank launched a fraud prevention taskforce to counter the unauthorized use of debit cards.[65] Kasisto and Moneystream use AI.\n"}
{"text":"Banks use AI to organize operations, for bookkeeping, investing in stocks, and managing properties. AI can react to changes when business is not taking place.[66] AI is used to combat fraud and financial crimes by monitoring behavioral patterns for any abnormal changes or anomalies.[67][68][69]\n"}
{"text":"The use of AI in applications such as online trading and decision making has changed major economic theories.[70] For example, AI-based buying and selling platforms estimate individualized demand and supply curves and thus enable individualized pricing. AI machines reduce information asymmetry in the market and thus make markets more efficient.[71] The application of artificial intelligence in the financial industry can alleviate the financing constraints of non-state-owned enterprises. Especially for smaller and more innovative enterprises.[72]\n"}
{"text":"Algorithmic trading involves the use of AI systems to make trading decisions at speeds orders of magnitude greater than any human is capable of, making millions of trades in a day without human intervention. Such high-frequency trading represents a fast-growing sector. Many banks, funds, and proprietary trading firms now have entire portfolios that are AI-managed. Automated trading systems are typically used by large institutional investors but include smaller firms trading with their own AI systems.[73]\n"}
{"text":"Large financial institutions use AI to assist with their investment practices. BlackRock's AI engine, Aladdin, is used both within the company and by clients to help with investment decisions. Its functions include the use of natural language processing to analyze text such as news, broker reports, and social media feeds. It then gauges the sentiment on the companies mentioned and assigns a score. Banks such as UBS and Deutsche Bank use SQREEM (Sequential Quantum Reduction and Extraction Model) to mine data to develop consumer profiles and match them with wealth management products.[74]\n"}
{"text":"Online lender Upstart uses machine learning for underwriting.[75]\n"}
{"text":"ZestFinance's Zest Automated Machine Learning (ZAML) platform is used for credit underwriting. This platform uses machine learning to analyze data including purchase transactions and how a customer fills out a form to score borrowers. The platform is particularly useful to assign credit scores to those with limited credit histories.[76]\n"}
{"text":"AI makes continuous auditing possible. Potential benefits include reducing audit risk, increasing the level of assurance, and reducing audit duration.[77][quantify]\n"}
{"text":"AI software, such as LaundroGraph which uses contemporary suboptimal datasets, could be used for anti-money laundering (AML).[78][79] AI can be used to \"develop the AML pipeline into a robust, scalable solution with a reduced false positive rate and high adaptability\".[80] A study about deep learning for AML identified \"key challenges for researchers\" to have \"access to recent real transaction data and scarcity of labelled training data; and data being highly imbalanced\" and suggests future research should bring-out \"explainability, graph deep learning using natural language processing (NLP), unsupervised and reinforcement learning to handle lack of labelled data; and joint research programs between the research community and industry to benefit from domain knowledge and controlled access to data\".[81]\n"}
{"text":"In the 1980s, AI started to become prominent in finance as expert systems were commercialized. For example, Dupont created 100 expert systems, which helped them to save almost $10 million per year.[82] One of the first systems was the Protrader expert system that predicted the 87-point drop in the Dow Jones Industrial Average in 1986. \"The major junctions of the system were to monitor premiums in the market, determine the optimum investment strategy, execute transactions when appropriate and modify the knowledge base through a learning mechanism.\"[83]\n"}
{"text":"One of the first expert systems to help with financial plans was PlanPowerm and Client Profiling System, created by Applied Expert Systems (APEX). It was launched in 1986. It helped create personal financial plans for people.[84]\n"}
{"text":"In the 1990s AI was applied to fraud detection. In 1993 FinCEN Artificial Intelligence System (FAIS) launched. It was able to review over 200,000 transactions per week and over two years it helped identify 400 potential cases of money laundering equal to $1 billion.[85] These expert systems were later replaced by machine learning systems.[86]\n"}
{"text":"AI can enhance entrepreneurial activity and AI is one of the most dynamic areas for start-ups, with significant venture capital flowing into AI.[87]\n"}
{"text":"AI facial recognition systems are used for mass surveillance, notably in China.[88][89]\n"}
{"text":"In 2019, Bengaluru, India deployed AI-managed traffic signals. This system uses cameras to monitor traffic density and adjust signal timing based on the interval needed to clear traffic.[90]\n"}
{"text":"Various countries are deploying AI military applications.[91] The main applications enhance command and control, communications, sensors, integration and interoperability.[92] Research is targeting intelligence collection and analysis, logistics, cyber operations, information operations, and semiautonomous and autonomous vehicles.[91] AI technologies enable coordination of sensors and effectors, threat detection and identification, marking of enemy positions, target acquisition, coordination and deconfliction of distributed Joint Fires between networked combat vehicles involving manned and unmanned teams.[92] AI was incorporated into military operations in Iraq and Syria.[91]\n"}
{"text":"In the 2023 Israel–Hamas war, Israel utilized AI system Habsora (translated: \"the gospel\") to quickly generate targets to strike, including Gazan residential homes that were suspected of affiliation to Hamas operatives. The combination of AI targeting technology with policy shift away from avoiding civilian targets resulted in unprecedented numbers of civilian deaths. IDF officials say the program addresses the previous issue of the air force running out of targets. Utilizing Habsora, officials say that suspected and junior Hamas members homes significantly expand the \"AI target bank.\" An internal source describes the process as a “mass assassination factory”[93][94]\n"}
{"text":"Worldwide annual military spending on robotics rose from US$5.1 billion in 2010 to US$7.5 billion in 2015.[95][96] Military drones capable of autonomous action are in wide use.[97] Many researchers avoid military applications.[92]\n"}
{"text":"AI in healthcare is often used for classification, to evaluate a CT scan or electrocardiogram or to identify high-risk patients for population health. AI is helping with the high-cost problem of dosing. One study suggested that AI could save $16 billion. In 2016, a study reported that an AI-derived formula derived the proper dose of immunosuppressant drugs to give to transplant patients.[98] Current research has indicated that non-cardiac vascular illnesses are also being treated with artificial intelligence (AI). For certain disorders, AI algorithms can assist with diagnosis, recommended treatments, outcome prediction, and patient progress tracking. As AI technology advances, it is anticipated that it will become more significant in the healthcare industry.[99]\n"}
{"text":"Microsoft's AI project Hanover helps doctors choose cancer treatments from among the more than 800 medicines and vaccines.[100][101] Its goal is to memorize all the relevant papers to predict which (combinations of) drugs will be most effective for each patient. Myeloid leukemia is one target. Another study reported on an AI that was as good as doctors in identifying skin cancers.[102] Another project monitors multiple high-risk patients by asking each patient questions based on data acquired from doctor/patient interactions.[103] In one study done with transfer learning, an AI diagnosed eye conditions similar to an ophthalmologist and recommended treatment referrals.[104]\n"}
{"text":"Another study demonstrated surgery with an autonomous robot. The team supervised the robot while it performed soft-tissue surgery, stitching together a pig's bowel judged better than a surgeon.[105]\n"}
{"text":"Artificial neural networks are used as clinical decision support systems for medical diagnosis,[106] such as in concept processing technology in EMR software.\n"}
{"text":"Other healthcare tasks thought suitable for an AI that are in development include:\n"}
{"text":"AI-enabled chatbots decrease the need for humans to perform basic call center tasks.[122]\n"}
{"text":"Machine learning in sentiment analysis can spot fatigue in order to prevent overwork.[122] Similarly, decision support systems can prevent industrial disasters and make disaster response more efficient.[123] For manual workers in material handling, predictive analytics may be used to reduce musculoskeletal injury.[124] Data collected from wearable sensors can improve workplace health surveillance, risk assessment, and research.[123][how?]\n"}
{"text":"AI can auto-code workers' compensation claims.[125][126] AI-enabled virtual reality systems can enhance safety training for hazard recognition.[123] AI can more efficiently detect accident near misses, which are important in reducing accident rates, but are often underreported.[127]\n"}
{"text":"AlphaFold 2 can determine the 3D structure of a (folded) protein in hours rather than the months required by earlier automated approaches and was used to provide the likely structures of all proteins in the human body and essentially all proteins known to science (more than 200 million).[128][129][130][131]\n"}
{"text":"Machine learning has been used for drug design. It has also been used for predicting molecular properties and exploring large chemical/reaction spaces.[132] Computer-planned syntheses via computational reaction networks, described as a platform that combines \"computational synthesis with AI algorithms to predict molecular properties\",[133] have been used to explore the origins of life on Earth,[134] drug-syntheses and developing routes for recycling 200 industrial waste chemicals into important drugs and agrochemicals (chemical synthesis design).[135] There is research about which types of computer-aided chemistry would benefit from machine learning.[136] It can also be used for \"drug discovery and development, drug repurposing, improving pharmaceutical productivity, and clinical trials\".[137] It has been used for the design of proteins with prespecified functional sites.[138][139]\n"}
{"text":"It has been used with databases for the development of a 46-day process to design, synthesize and test a drug which inhibits enzymes of a particular gene, DDR1. DDR1 is involved in cancers and fibrosis which is one reason for the high-quality datasets that enabled these results.[140]\n"}
{"text":"There are various types of applications for machine learning in decoding human biology, such as helping to map gene expression patterns to functional activation patterns[141] or identifying functional DNA motifs.[142] It is widely used in genetic research.[143]\n"}
{"text":"There also is some use of machine learning in synthetic biology,[144][145] disease biology,[145] nanotechnology (e.g. nanostructured materials and bionanotechnology),[146][147] and materials science.[148][149][150]\n"}
{"text":"There are also prototype robot scientists, including robot-embodied ones like the two Robot Scientists, which show a form of \"machine learning\" not commonly associated with the term.[151][152]\n"}
{"text":"Similarly, there is research and development of biological \"wetware computers\" that can learn (e.g. for use as biosensors) and/or implantation into an organism's body (e.g. for use to control prosthetics).[153][154][155] Polymer-based artificial neurons operate directly in biological environments and define biohybrid neurons made of artificial and living components.[156][157]\n"}
{"text":"Moreover, if whole brain emulation is possible via both scanning and replicating the, at least, bio-chemical brain – as premised in the form of digital replication in The Age of Em, possibly using physical neural networks – that may have applications as or more extensive than e.g. valued human activities and may imply that society would face substantial moral choices, societal risks and ethical problems[158][159] such as whether (and how) such are built, sent through space and used compared to potentially competing e.g. potentially more synthetic and/or less human and/or non/less-sentient types of artificial/semi-artificial intelligence.[additional citation(s) needed] An alternative or additive approach to scanning are types of reverse engineering of the brain.[160][161]\n"}
{"text":"A subcategory of artificial intelligence is embodied,[162][163] some of which are mobile robotic systems that each consist of one or multiple robots that are able to learn in the physical world.\n"}
{"text":"However, biological computers, even if both highly artificial and intelligent, are typically distinguished from synthetic, often silicon-based, computers – they could however be combined or used for the design of either. Moreover, many tasks may be carried out inadequately by artificial intelligence even if its algorithms were transparent, understood, bias-free, apparently effective, and goal-aligned and its trained data sufficiently large and cleansed – such as in cases were the underlying or available metrics, values or data are inappropriate. Computer-aided is a phrase used to describe human activities that make use of computing as tool in more comprehensive activities and systems such as AI for narrow tasks or making use of such without substantially relying on its results (see also: human-in-the-loop).[citation needed] A study described the biological as a limitation of AI with \"as long as the biological system cannot be understood, formalized, and imitated, we will not be able to develop technologies that can mimic it\" and that if it was understood this does not mean there being \"a technological solution to imitate natural intelligence\".[164] Technologies that integrate biology and are often AI-based include biorobotics.\n"}
{"text":"Artificial intelligence is used in astronomy to analyze increasing amounts of available data[165][166] and applications, mainly for \"classification, regression, clustering, forecasting, generation, discovery, and the development of new scientific insights\" for example for discovering exoplanets, forecasting solar activity, and distinguishing between signals and instrumental effects in gravitational wave astronomy.[167] It could also be used for activities in space such as space exploration, including analysis of data from space missions, real-time science decisions of spacecraft, space debris avoidance,[168] and more autonomous operation.[169][170][171][166]\n"}
{"text":"In the search for extraterrestrial intelligence (SETI), machine learning has been used in attempts to identify artificially generated electromagnetic waves in available data[172][173] – such as real-time observations[174] – and other technosignatures, e.g. via anomaly detection.[175] In ufology, the SkyCAM-5 project headed by Prof. Hakan Kayal[176] and the Galileo Project headed by Prof. Avi Loeb use machine learning to detect and classify peculiar types of UFOs.[177][178][179][180][181] The Galileo Project also seeks to detect two further types of potential extraterrestrial technological signatures with the use of AI: 'Oumuamua-like interstellar objects, and non-manmade artificial satellites.[182][183]\n"}
{"text":"Loeb has speculated that one type of technological equipment the project may detect could be \"AI astronauts\"[184] and in 2021 – in an opinion piece – that AI \"will\" \"supersede natural intelligence\",[185] while Martin Rees stated that there \"may\" be more civilizations than thought with the \"majority of them\" being artificial.[186] In particular, mid/far future or non-human applications of artificial intelligence could include advanced forms of artificial general intelligence that engages in space colonization or more narrow spaceflight-specific types of AI. In contrast, there have been concerns in relation to potential AGI or AI capable of embryo space colonization, or more generally natural intelligence-based space colonization, such as \"safety of encounters with an alien AI\",[187][188] suffering risks (or inverse goals),[189][190] moral license/responsibility in respect to colonization-effects,[191] or AI gone rogue (e.g. as portrayed with fictional David8 and HAL 9000). See also: space law and space ethics. Loeb has described the possibility of \"AI astronauts\" that engage in \"supervised evolution\" (see also: directed evolution, uplift, directed panspermia and space colonization).[192]\n"}
{"text":"It can also be used to produce datasets of spectral signatures of molecules that may be involved in the atmospheric production or consumption of particular chemicals – such as phosphine possibly detected on Venus – which could prevent miss assignments and, if accuracy is improved, be used in future detections and identifications of molecules on other planets.[193]\n"}
{"text":"Machine learning can help to restore and attribute ancient texts.[194] It can help to index texts for example to enable better and easier searching[195] and classification of fragments.[196]\n"}
{"text":"\nArtificial intelligence can also be used to investigate genomes to uncover genetic history, such as interbreeding between archaic and modern humans by which for example the past existence of a ghost population, not Neanderthal or Denisovan, was inferred.[197] "}
{"text":"\nIt can also be used for \"non-invasive and non-destructive access to internal structures of archaeological remains\".[198] "}
{"text":"A deep learning system was reported to learn intuitive physics from visual data (of virtual 3D environments) based on an unpublished approach inspired by studies of visual cognition in infants.[199][200] Other researchers have developed a machine learning algorithm that could discover sets of basic variables of various physical systems and predict the systems' future dynamics from video recordings of their behavior.[201][202] In the future, it may be possible that such can be used to automate the discovery of physical laws of complex systems.[201]\n"}
{"text":"AI could be used for materials optimization and discovery such as the discovery of stable materials and the prediction of their crystal structure.[203][204][205]\n"}
{"text":"In November 2023, researchers at Google DeepMind and Lawrence Berkeley National Laboratory announced that they had developed an AI system known as GNoME. This system has contributed to materials science by discovering over 2 million new materials within a relatively short timeframe. GNoME employs deep learning techniques to efficiently explore potential material structures, achieving a significant increase in the identification of stable inorganic crystal structures. The system's predictions were validated through autonomous robotic experiments, demonstrating a noteworthy success rate of 71%. The data of newly discovered materials is publicly available through the Materials Project database, offering researchers the opportunity to identify materials with desired properties for various applications. This development has implications for the future of scientific discovery and the integration of AI in material science research, potentially expediting material innovation and reducing costs in product development. The use of AI and deep learning suggests the possibility of minimizing or eliminating manual lab experiments and allowing scientists to focus more on the design and analysis of unique compounds.[206][207][208]\n"}
{"text":"Machine learning is used in diverse types of reverse engineering. For example, machine learning has been used to reverse engineer a composite material part, enabling unauthorized production of high quality parts,[209] and for quickly understanding the behavior of malware.[210][211][212] It can be used to reverse engineer artificial intelligence models.[213] It can also design components by engaging in a type of reverse engineering of not-yet existent virtual components such as inverse molecular design for particular desired functionality[214] or protein design for prespecified functional sites.[138][139] Biological network reverse engineering could model interactions in a human understandable way, e.g. bas on time series data of gene expression levels.[215]\n"}
{"text":"AI is a mainstay of law-related professions. Algorithms and machine learning do some tasks previously done by entry-level lawyers.[216] While its use is common, it is not expected to replace most work done by lawyers in the near future.[217]\n"}
{"text":"The electronic discovery industry uses machine learning to reduce manual searching.[218]\n"}
{"text":"COMPAS is a commercial system used by U.S. courts to assess the likelihood of recidivism.[219]\n"}
{"text":"One concern relates to algorithmic bias, AI programs may become biased after processing data that exhibits bias.[220] ProPublica claims that the average COMPAS-assigned recidivism risk level of black defendants is significantly higher than that of white defendants.[219]\n"}
{"text":"In 2019, the city of Hangzhou, China established a pilot program artificial intelligence-based Internet Court to adjudicate disputes related to ecommerce and internet-related intellectual property claims.[221]: 124  Parties appear before the court via videoconference and AI evaluates the evidence presented and applies relevant legal standards.[221]: 124 \n"}
{"text":"Another application of AI is in human resources. AI can screen resumes and rank candidates based on their qualifications, predict candidate success in given roles, and automate repetitive communication tasks via chatbots.[222]\n"}
{"text":"AI has simplified the recruiting /job search process for both recruiters and job seekers. According to Raj Mukherjee from Indeed, 65% of job searchers search again within 91 days after hire. An AI-powered engine streamlines the complexity of job hunting by assessing information on job skills, salaries, and user tendencies, matching job seekers to the most relevant positions. Machine intelligence calculates appropriate wages and highlights resume information for recruiters using NLP, which extracts relevant words and phrases from text. Another application is an AI resume builder that compiles a CV in 5 minutes.[223] Chatbots assist website visitors and refine workflows.\n"}
{"text":"AI underlies avatars (automated online assistants) on web pages.[224] It can reduce operation and training costs.[224] Pypestream automated customer service for its mobile application to streamline communication with customers.[225]\n"}
{"text":"A Google app analyzes language and converts speech into text. The platform can identify angry customers through their language and respond appropriately.[226] Amazon uses a chatbot for customer service that can perform tasks like checking the status of an order, cancelling orders, offering refunds and connecting the customer with a human representative.[227]\n"}
{"text":"In the hospitality industry, AI is used to reduce repetitive tasks, analyze trends, interact with guests, and predict customer needs.[228] AI hotel services come in the form of a chatbot,[229] application, virtual voice assistant and service robots.\n"}
{"text":"AI applications analyze media content such as movies, TV programs, advertisement videos or user-generated content. The solutions often involve computer vision.\n"}
{"text":"Typical scenarios include the analysis of images using object recognition or face recognition techniques, or the analysis of video for scene recognizing scenes, objects or faces. AI-based media analysis can facilitate media search, the creation of descriptive keywords for content, content policy monitoring (such as verifying the suitability of content for a particular TV viewing time), speech to text for archival or other purposes, and the detection of logos, products or celebrity faces for ad placement.\n"}
{"text":"Deep-fakes can be used for comedic purposes but are better known for fake news and hoaxes.\n"}
{"text":"In January 2016,[242] the Horizon 2020 program financed the InVID Project[243][244] to help journalists and researchers detect fake documents, made available as browser plugins.[245][246]\n"}
{"text":"In June 2016, the visual computing group of the Technical University of Munich and from Stanford University developed Face2Face,[247] a program that animates photographs of faces, mimicking the facial expressions of another person. The technology has been demonstrated animating the faces of people including Barack Obama and Vladimir Putin. Other methods have been demonstrated based on deep neural networks, from which the name deep fake was taken.\n"}
{"text":"In September 2018, U.S. Senator Mark Warner proposed to penalize social media companies that allow sharing of deep-fake documents on their platforms.[248]\n"}
{"text":"In 2018, Darius Afchar and Vincent Nozick found a way to detect faked content by analyzing the mesoscopic properties of video frames.[249] DARPA gave 68 million dollars to work on deep-fake detection.[249]\n"}
{"text":"Audio deepfakes[250][251] and AI software capable of detecting deep-fakes and cloning human voices have been developed.[252][253]\n"}
{"text":"Respeecher is a program that enables one person to speak with the voice of another.\n"}
{"text":"AI algorithms have been used to detect deepfake videos.[254][255]\n"}
{"text":"Artificial Intelligence is also starting to be used in video production, with tools and softwares being developed that utilize generative AI in order to create new video, or alter existing video. Some of the major tools that are being used in these processes currently are DALL-E, Midjourney, and Runway.[256]  Waymark Studios utilized the tools offered by both DALL-E and Midjourney to create a fully AI generated film called The Frost in the summer of 2023.[256] Waymark Studios is experimenting with using these AI tools to generate advertisements and commercials for companies in mere seconds.[256]  Yves Bergquist, a director of the AI \u0026 Neuroscience in Media Project at USC's Entertainment Technology Center, says post production crews in Hollywood are already using generative AI, and predicts that in the future more companies will embrace this new technology.[257]\n"}
{"text":"AI has been used to compose music of various genres.\n"}
{"text":"David Cope created an AI called Emily Howell that managed to become well known in the field of algorithmic computer music.[258] The algorithm behind Emily Howell is registered as a US patent.[259]\n"}
{"text":"In 2012, AI Iamus created the first complete classical album.[260]\n"}
{"text":"AIVA (Artificial Intelligence Virtual Artist), composes symphonic music, mainly classical music for film scores.[261] It achieved a world first by becoming the first virtual composer to be recognized by a musical professional association.[262]\n"}
{"text":"Melomics creates computer-generated music for stress and pain relief.[263]\n"}
{"text":"At Sony CSL Research Laboratory, the Flow Machines software creates pop songs by learning music styles from a huge database of songs. It can compose in multiple styles.\n"}
{"text":"The Watson Beat uses reinforcement learning and deep belief networks to compose music on a simple seed input melody and a select style. The software was open sourced[264] and musicians such as Taryn Southern[265] collaborated with the project to create music.\n"}
{"text":"South Korean singer Hayeon's debut song, \"Eyes on You\" was composed using AI which was supervised by real composers, including NUVO.[266]\n"}
{"text":"Narrative Science sells computer-generated news and reports. It summarizes sporting events based on statistical data from the game. It also creates financial reports and real estate analyses.[267] Automated Insights generates personalized recaps and previews for Yahoo Sports Fantasy Football.[268]\n"}
{"text":"Yseop, uses AI to turn structured data into natural language comments and recommendations. Yseop writes financial reports, executive summaries, personalized sales or marketing documents and more in multiple languages, including English, Spanish, French, and German.[269]\n"}
{"text":"TALESPIN made up stories similar to the fables of Aesop. The program started with a set of characters who wanted to achieve certain goals. The story narrated their attempts to satisfy these goals.[citation needed] Mark Riedl and Vadim Bulitko asserted that the essence of storytelling was experience management, or \"how to balance the need for a coherent story progression with user agency, which is often at odds\".[270]\n"}
{"text":"While AI storytelling focuses on story generation (character and plot), story communication also received attention. In 2002, researchers developed an architectural framework for narrative prose generation. They faithfully reproduced text variety and complexity on stories such as Little Red Riding Hood.[271] In 2016, a Japanese AI co-wrote a short story and almost won a literary prize.[272]\n"}
{"text":"South Korean company Hanteo Global uses a journalism bot to write articles.[273]\n"}
{"text":"Literary authors are also exploring uses of AI. An example is David Jhave Johnston's work ReRites (2017-2019), where the poet created a daily rite of editing the poetic output of a neural network to create a series of performances and publications.\n"}
{"text":"In 2010, artificial intelligence used baseball statistics to automatically generate news articles. This was launched by The Big Ten Network using a software from Narrative Science.[274]\n"}
{"text":"After being unable to cover every Minor League Baseball game with a large team of people, Associated Press collaborated with Automated Insights in 2016 to create game recaps that were automated by artificial intelligence.[275]\n"}
{"text":"UOL in Brazil expanded the use of AI in their writing. Rather than just generating news stories, they programmed the AI to include commonly searched words on Google.[275]\n"}
{"text":"El Pais, a Spanish news site that covers many things including sports, allows users to make comments on each news article. They use the Perspective API to moderate these comments and if the software deems a comment to contain toxic language, the commenter will be forced to change their comment in order to publish it.[275]\n"}
{"text":"A local Dutch media group used AI to create automatic coverage of amateur soccer, set to cover 60,000 games in just a single season. NDC partnered with United Robots to create this algorithm and cover what would have never been able to be done before without an extremely large team.[275]\n"}
{"text":"Lede AI has been used in 2023 to take scores from high school football games to generate stories automatically for the local news paper. This was met with a lot of criticism from readers for the very robotic diction that was published. With some descriptions of games being a \"close encounter of the athletic kind,\" readers were not pleased and let the publishing company, Gannett, know on social media. Gannett has since halted their used of Lede AI until they come up with a solution for what they call an experiment.[276]\n"}
{"text":" Millions of its articles have been edited by bots[280] which however are usually not artificial intelligence software. Many AI platforms use Wikipedia data,[281] mainly for training machine learning applications. There is research and development of various artificial intelligence applications for Wikipedia such as for identifying outdated sentences,[282] detecting covert vandalism[283] or recommending articles and tasks to new editors.\n"}
{"text":"Machine translation .mw-parser-output div.crossreference{padding-left:0}(see above) has also be used for translating Wikipedia articles and could play a larger role in creating, updating, expanding, and generally improving articles in the future. A content translation tool allows editors of some Wikipedias to more easily translate articles across several select languages.[284][285]\n"}
{"text":"In video games, AI is routinely used to generate behavior in non-player characters (NPCs). In addition, AI is used for pathfinding. Some researchers consider NPC AI in games to be a \"solved problem\" for most production tasks.[who?] Games with less typical AI include the AI director of Left 4 Dead (2008) and the neuroevolutionary training of platoons in Supreme Commander 2 (2010).[286][287] AI is also used in Alien Isolation (2014) as a way to control the actions the Alien will perform next.[288]\n"}
{"text":"Kinect, which provides a 3D body–motion interface for the Xbox 360 and the Xbox One, uses algorithms that emerged from AI research.[289][which?]\n"}
{"text":"AI has been used to produce visual art. The first AI art program, called AARON, was developed by Harold Cohen in 1968[290] with the goal of being able to code the act of drawing.\nIt started by creating simple black and white drawings, and later to paint using special brushes and dyes that were chosen by the program itself without mediation from Cohen.[291]\n"}
{"text":"AI like \"Disco Diffusion\", \"DALL·E\" (1 and 2),[292][293] Stable Diffusion,[293][294] Imagen,[295] \"Dream by Wombo\",[296][297][298] Midjourney[299][300] has been used for visualizing conceptual inputs such as song lyrics, certain texts or specific imagined concepts (or imaginations) in artistic ways or artistic images in general.[301] Some of the tools also allow users to input images and various parameters e.g. to display an object or product in various environments, some can replicate artistic styles of popular artists, and some can create elaborate artistic images from rough sketches.\n"}
{"text":"Since their design in 2014, generative adversarial networks (GANs) have been used by AI artists. GAN computer programming, generates technical images through machine learning frameworks that surpass the need for human operators.[290] Examples of GAN programs that generate art include Artbreeder and DeepDream.\n"}
{"text":"In addition to the creation of original art, research methods that utilize AI have been generated to quantitatively analyze digital art collections. Although the main goal of the large-scale digitization of artwork in the past few decades was to allow for accessibility and exploration of these collections, the use of AI in analyzing them has brought about new research perspectives.[302]\nTwo computational methods, close reading and distant viewing, are the typical approaches used to analyze digitized art.[303] While distant viewing includes the analysis of large collections, close reading involves one piece of artwork.\n"}
{"text":"Researchers have also introduced models that predict emotional responses to art.[304]\n"}
{"text":"AI has been in use since the early 2000s, most notably by a system designed by Pixar called \"Genesis\".[305] It was designed to learn algorithms and create 3D models for its characters and props. Notable movies that used this technology included Up and The Good Dinosaur.[306] AI has been used less ceremoniously in recent years. In 2023, it was revealed Netflix of Japan was using AI to generate background images for their upcoming show to be met with backlash online.[307]  In recent years, motion capture became an easily accessible form of AI animation. For example, Move AI is a program built to capture any human movement and reanimate it in its animation program using learning AI.[308]\n"}
{"text":"Artificially intelligent computer-aided design (CAD) can use text-to-3D, image-to-3D, and video-to-3D to help in 3D modeling.[309]  Ai CAD libraries could also be developed using linked open data of schematics  and diagrams.[310]  Ai CAD assistants are used as tools to help streamline workflow.[311]\n"}
{"text":"Power electronics converters are used in renewable energy, energy storage, electric vehicles and high-voltage direct current transmission. These converters are failure-prone, which can interrupt service and require costly maintenance or catastrophic consequences in mission critical applications.[citation needed] AI can guide the design process for reliable power electronics converters, by calculating exact design parameters that ensure the required lifetime.[312]\n"}
{"text":"Machine learning can be used for energy consumption prediction and scheduling, e.g. to help with renewable energy intermittency management (see also: smart grid and climate change mitigation in the power grid).[313][314][315][316][better source needed]\n"}
{"text":"Many telecommunications companies make use of heuristic search to manage their workforces. For example, BT Group deployed heuristic search[317] in an application that schedules 20,000 engineers. Machine learning is also used for speech recognition (SR), including of voice-controlled devices, and SR-related transcription, including of videos.[318][319]\n"}
{"text":"Artificial intelligence has been combined with digital spectrometry by IdeaCuria Inc.,[320][321] enable applications such as at-home water quality monitoring.\n"}
{"text":"In the 1990s early AIs controlled Tamagotchis and Giga Pets, the Internet, and the first widely released robot, Furby. Aibo was a domestic robot in the form of a robotic dog with intelligent features and autonomy.\n"}
{"text":"Mattel created an assortment of AI-enabled toys that \"understand\" conversations, give intelligent responses, and learn.[322]\n"}
{"text":"Oil and gas companies have used artificial intelligence tools to automate functions, foresee equipment issues, and increase oil and gas output.[323][324]\n"}
{"text":"AI in transport is expected to provide safe, efficient, and reliable transportation while minimizing the impact on the environment and communities. The major development challenge is the complexity of transportation systems that involves independent components and parties, with potentially conflicting objectives.[325]\n"}
{"text":"AI-based fuzzy logic controllers operate gearboxes. For example, the 2006 Audi TT, VW Touareg[citation needed] and VW Caravell feature the DSP transmission. A number of Škoda variants (Škoda Fabia) include a fuzzy logic-based controller. Cars have AI-based driver-assist features such as self-parking and adaptive cruise control.\n"}
{"text":"There are also prototypes of autonomous automotive public transport vehicles such as electric mini-buses[326][327][328][329] as well as autonomous rail transport in operation.[330][331][332]\n"}
{"text":"There also are prototypes of autonomous delivery vehicles, sometimes including delivery robots.[333][334][335][336][337][338][339]\n"}
{"text":"Transportation's complexity means that in most cases training an AI in a real-world driving environment is impractical. Simulator-based testing can reduce the risks of on-road training.[340]\n"}
{"text":"AI underpins self-driving vehicles. Companies involved with AI include Tesla, Waymo, and General Motors. AI-based systems control functions such as braking, lane changing, collision prevention, navigation and mapping.[341]\n"}
{"text":"Autonomous trucks are in the testing phase. The UK government passed legislation to begin testing of autonomous truck platoons in 2018.[342] A group of autonomous trucks follow closely behind each other. German corporation Daimler is testing its Freightliner Inspiration.[343]\n"}
{"text":"Autonomous vehicles require accurate maps to be able to navigate between destinations.[344] Some autonomous vehicles do not allow human drivers (they have no steering wheels or pedals).[345]\n"}
{"text":"AI has been used to optimize traffic management, which reduces wait times, energy use, and emissions by as much as 25 percent.[346]\n"}
{"text":"Smart traffic lights have been developed at Carnegie Mellon since 2009.  Professor Stephen Smith has started a company since then Surtrac that has installed smart traffic control systems in 22 cities.  It costs about $20,000 per intersection to install. Drive time has been reduced by 25% and traffic jam waiting time has been reduced by 40% at the intersections it has been installed.[347]\n"}
{"text":"The Royal Australian Air Force (RAAF) Air Operations Division (AOD) uses AI for expert systems. AIs operate as surrogate operators for combat and training simulators, mission management aids, support systems for tactical decision making, and post processing of the simulator data into symbolic summaries.[348]\n"}
{"text":"Aircraft simulators use AI for training aviators. Flight conditions can be simulated that allow pilots to make mistakes without risking themselves or expensive aircraft. Air combat can also be simulated.\n"}
{"text":"AI can also be used to operate planes analogously to their control of ground vehicles. Autonomous drones can fly independently or in swarms.[349]\n"}
{"text":"AOD uses the Interactive Fault Diagnosis and Isolation System, or IFDIS, which is a rule-based expert system using information from TF-30 documents and expert advice from mechanics that work on the TF-30. This system was designed to be used for the development of the TF-30 for the F-111C. The system replaced specialized workers. The system allowed regular workers to communicate with the system and avoid mistakes, miscalculations, or having to speak to one of the specialized workers.\n"}
{"text":"Speech recognition allows traffic controllers to give verbal directions to drones.\n"}
{"text":"Artificial intelligence supported design of aircraft,[350] or AIDA, is used to help designers in the process of creating conceptual designs of aircraft. This program allows the designers to focus more on the design itself and less on the design process. The software also allows the user to focus less on the software tools. The AIDA uses rule-based systems to compute its data. This is a diagram of the arrangement of the AIDA modules. Although simple, the program is proving effective.\n"}
{"text":"In 2003 a Dryden Flight Research Center project created software that could enable a damaged aircraft to continue flight until a safe landing can be achieved.[351] The software compensated for damaged components by relying on the remaining undamaged components.[352]\n"}
{"text":"The 2016 Intelligent Autopilot System combined apprenticeship learning and behavioral cloning whereby the autopilot observed low-level actions required to maneuver the airplane and high-level strategy used to apply those actions.[353]\n"}
{"text":"Neural networks are used by situational awareness systems in ships and boats.[354] There also are autonomous boats.\n"}
{"text":"Autonomous ships that monitor the ocean, AI-driven satellite data analysis, passive acoustics[355] or remote sensing and other applications of environmental monitoring make use of machine learning.[356][357][358][171]\n"}
{"text":"For example, \"Global Plastic Watch\" is an AI-based satellite monitoring-platform for analysis/tracking of plastic waste sites to help prevention of plastic pollution – primarily ocean pollution – by helping identify who and where mismanages plastic waste, dumping it into oceans.[359][360]\n"}
{"text":"Machine learning can be used to spot early-warning signs of disasters and environmental issues, possibly including natural pandemics,[361][362] earthquakes,[363][364][365] landslides,[366] heavy rainfall,[367] long-term water supply vulnerability,[368] tipping-points of ecosystem collapse,[369] cyanobacterial bloom outbreaks,[370] and droughts.[371][372][373]\n"}
{"text":"AI can be used for real-time code completion, chat, and automated test generation. These tools are typically integrated with editors and IDEs as plugins. They differ in functionality, quality, speed, and approach to privacy.[374]\n"}
{"text":"Code suggestions could be incorrect, and should be carefully reviewed by software developers before accepted.\n"}
{"text":"GitHub Copilot is an artificial intelligence model developed by GitHub and OpenAI that is able to autocomplete code in multiple programming languages.[375] Price for individuals: $10/mo or $100/yr, with one free month trial.\n"}
{"text":"Tabnine was created by Jacob Jackson and was originally owned by Tabnine company. In late 2019, Tabnine was acquired by Codota.[376] Tabnine tool is available as plugin to most popular IDEs. It offers multiple pricing options, including limited \"starter\" free version.[377]\n"}
{"text":"CodiumAI by CodiumAI, small startup in Tel Aviv, offers automated test creation. Currently supports Python, JS, and TS.[378]\n"}
{"text":"Ghostwriter by Replit offers code completion and chat.[379] They have multiple pricing plans, including a free one and a \"Hacker\" plan for $7/month.\n"}
{"text":"CodeWhisperer by Amazon collects individual users' content, including files open in the IDE. They claim to focus on security both during transmission and when storing.[380] Individual plan is free, professional plan is $19/user/month.\n"}
{"text":"Other tools: SourceGraph Cody, CodeCompleteFauxPilot, Tabby[374]\n"}
{"text":"AI can be used to create other AIs. For example, around November 2017, Google's AutoML project to evolve new neural net topologies created NASNet, a system optimized for ImageNet and POCO F1. NASNet's performance exceeded all previously published performance on ImageNet.[381]\n"}
{"text":"Machine learning has been used for noise-cancelling in quantum technology,[382] including quantum sensors.[383] Moreover, there is substantial research and development of using quantum computers with machine learning algorithms. For example, there is a prototype, photonic, .mw-parser-output .tooltip-dotted{border-bottom:1px dotted;cursor:help}quantum memristive device for neuromorphic (quantum-)computers (NC)/artificial neural networks and NC-using quantum materials with some variety of potential neuromorphic computing-related applications,[384][385] and quantum machine learning is a field with some variety of applications under development. AI could be used for quantum simulators which may have the application of solving physics and chemistry[386][387] problems as well as for quantum annealers for training of neural networks for AI applications.[388] There may also be some usefulness in chemistry, e.g. for drug discovery, and in materials science, e.g. for materials optimization/discovery (with possible relevance to quantum materials manufacturing[204][205]).[389][390][391][better source needed]\n"}
{"text":"AI researchers have created many tools to solve the most difficult problems in computer science. Many of their inventions have been adopted by mainstream computer science and are no longer considered AI. All of the following were originally developed in AI laboratories:[392]\n"}
{"text":"Business websites and social media platforms for businesses like use chatbots for customer interactions like helping in answering frequently asked questions. Chatbots offers 24/7 support and replaces humans thereby helping in cutting business costs.\n"}
{"text":"An optical character reader is used in the extraction of data in business documents like invoices and receipts. It can also be used in business contract documents e.g. employment agreements to extract critical data like employment terms, delivery terms, termination clauses, etc.[393]\n"}
